(()=>{'use strict';const r=document.documentElement,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],t=(th,en)=>r.lang==='th'?th:en;
const roles=window.LDS_ROLES;
function url(changes){const u=new URL(location.href);Object.entries(changes).forEach(([k,v])=>u.searchParams.set(k,v));history.replaceState(null,'',u)}
function theme(pref,save=true){const dark=pref==='dark'||(pref==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);r.dataset.themePreference=pref;r.dataset.theme=dark?'dark':'light';r.style.colorScheme=r.dataset.theme;const labels={th:{system:'อัตโนมัติ',light:'สว่าง',dark:'มืด'},en:{system:'Auto',light:'Light',dark:'Dark'}};$('#theme-label').textContent=labels[r.lang][pref];$('#theme-icon').textContent={system:'◐',light:'☀',dark:'◑'}[pref];document.querySelector('meta[name=theme-color]').content=dark?'#11191D':'#F6F7F3';if(save)try{localStorage.setItem('lds-theme',pref)}catch{}url({theme:pref})}
function language(lang,save=true){r.lang=lang;$('#language').textContent=lang==='th'?'EN':'TH';document.querySelector('meta[property="og:locale"]').content=lang==='th'?'th_TH':'en_US';if(save)try{localStorage.setItem('lds-lang',lang)}catch{}url({lang});render(r.dataset.role)}
function render(id){if(!roles[id])id='design';const x=roles[id],lang=r.lang==='th'?0:1;r.dataset.role=id;$$('.tabs [data-role]').forEach((b,i)=>{const on=b.dataset.role===id;b.id='role-'+b.dataset.role;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1;if(on)$('#role-panel').setAttribute('aria-labelledby',b.id)});$('#role-label').textContent=id==='evidence'?'Data / Evidence':id[0].toUpperCase()+id.slice(1);$('#role-title').textContent=x.title[lang];$('#role-description').textContent=x.description[lang];$('#role-next').textContent=x.next;$('#role-prompt').textContent=x.prompt;$('#baseline-title').textContent=x.baseline[lang];$('#baseline-body').textContent=x.baseline[lang+2];$('#assisted-title').textContent=x.assisted[lang];$('#assisted-body').textContent=x.assisted[lang+2];url({role:id})}
function announce(th,en){$('#status').textContent=t(th,en)}
$$('.tabs [data-role]').forEach(b=>{b.addEventListener('click',()=>render(b.dataset.role));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const a=$$('.tabs [data-role]'),i=a.indexOf(b),n=e.key==='Home'?0:e.key==='End'?a.length-1:e.key==='ArrowRight'?(i+1)%a.length:(i-1+a.length)%a.length;a[n].click();a[n].focus()})});
$('#theme').onclick=()=>{const a=['system','light','dark'],c=r.dataset.themePreference||'system';theme(a[(a.indexOf(c)+1)%a.length]);announce('เปลี่ยนธีมแล้ว','Theme changed')};$('#language').onclick=()=>{language(r.lang==='th'?'en':'th');announce('เปลี่ยนภาษาแล้ว','Language changed')};$('#copy').onclick=async()=>{const v=$('#role-prompt').textContent;try{await navigator.clipboard.writeText(v);announce('คัดลอก prompt แล้ว','Prompt copied')}catch{const range=document.createRange();range.selectNodeContents($('#role-prompt'));const s=getSelection();s.removeAllRanges();s.addRange(range);$('#role-prompt').focus();announce('เลือกข้อความแล้ว ใช้คำสั่งคัดลอกได้เลย','Prompt selected; use your copy command')}};
const p=new URL(location.href).searchParams;language(r.lang,false);theme(r.dataset.themePreference||p.get('theme')||'system',false);render(roles[r.dataset.role]?r.dataset.role:'design');matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(r.dataset.themePreference==='system')theme('system',false)});
})();
