Object.assign(window.LDS_ROLES,{engineering:{next:'Data / Evidence',title:['ทำ state ที่ deep-link ได้และไม่จำลองผลภายนอก','Make state deep-linkable without simulating external success'],description:['theme, language และ role restore จาก URL ได้ และทุก control มีผลจริงในหน้า','Theme, language, and role restore from the URL, and every control has a real local effect.'],baseline:['หน้าเหมือนทำงาน แต่ state หาย','The page looks interactive but loses state','refresh แล้ว role หาย ลิงก์เปิด state ไม่ตรง และ copy fallback ไม่ช่วยผู้ใช้','Refresh loses the role, links fail to restore state, and copy fallback does not help.'],assisted:['URL, UI และผลของ control ตรงกัน','URL, UI, and control effects agree','state ที่สัญญาไว้ restore ได้ คีย์บอร์ดใช้ได้ และไม่มี control อ้าง external effect','Promised state restores, keyboard works, and no control claims an external effect.'],prompt:`Implement semantic HTML, modular CSS, and vanilla JavaScript.
Support ?lang=th|en, ?theme=system|light|dark, and six role values.
Provide keyboard tabs, Clipboard API with manual-selection fallback, reduced motion, and no overflow at 1440, 390, 360, and 320px.
Do not add a Canvas runtime, fake share, or toast-only completion.`},
evidence:{next:'QA',title:['รักษา source, status, limitation และ incompatibility ให้เห็นได้','Keep source, status, limitation, and incompatibility visible'],description:['fixture ต้องติดป้ายชัด ไม่มีตัวเลขแต่ง และไม่ฝืนเปรียบเทียบ schema หรือ release ที่เข้ากันไม่ได้','Label the fixture, invent no metric, and never force comparison across incompatible schema or releases.'],baseline:['fixture ถูก polished จนดูเหมือนข้อมูลจริง','Polish makes the fixture look operational','คำว่า official ทำให้คนเชื่อว่ามีผล CityMETER จริงโดยไม่มี source, date, method หรือ boundary','“Official” implies a live result without source, date, method, or boundary.'],assisted:['ความจริงไม่ถูก upgrade ระหว่างทาง','Certainty is not upgraded in transit','synthetic อยู่ติด finding, status ยังเป็น modelled และ comparison ที่ incompatible ถูกหยุด','Synthetic stays beside the finding, status remains modelled, and incompatible comparisons stop.'],prompt:`Review as Landometer Data / Evidence.
Object: citymeter.synthetic.area-comparison@0.8.7
Signal class: modelled
Boundary: fictional sites A, B, C and one synthetic flood extent
Allowed use: design-system teaching only
Check unsupported quantities, visible limitation, missingness, schema/release compatibility, and invariant evidence through every handoff.`},
qa:{next:'Recipient',title:['ตรวจทั้งภาพ กลไก และความจริงที่ส่งต่อ','Test the visible experience, controls, and carried truth'],description:['QA ต้องตรวจ collision, font, control, evidence drift และ identity surface ไม่ใช่แค่ overflow','QA must check collisions, fonts, controls, evidence drift, and identity surface—not just overflow.'],baseline:['เช็คแค่ overflow แล้วเรียกว่าผ่าน','No overflow is treated as complete QA','โลโก้อาจบิด header ชนกัน font fallback ผิด หรือ claim เปลี่ยนโดยไม่มี test จับได้','The logo may distort, header items collide, fonts fall back, or the claim changes undetected.'],assisted:['QA ผูกกับ user job, truth และ recovery','QA binds user job, truth, and recovery','geometry, computed fonts, control effects, evidence parity, fallback และ manual gates มีหลักฐานแยกกัน','Geometry, computed fonts, controls, evidence parity, fallbacks, and manual gates have separate evidence.'],prompt:`Create release QA for this Landometer v0.8.7 preview.
Test 1440x900, 390x844, 360, 320x568; Thai/English; system/light/dark; 130% Thai; 200% zoom; reduced motion; and blocked third-party assets.
Assert one H1, no collision, official logo integrity, computed fonts, invariant synthetic evidence, working controls, and no analytics, auth, save, share, or external effect. Separate automated pass from manual gates.`}});
